[groups]
ml = grace, henry, irene
payment = alice, bob, carol
web = david, eve, frank

[/]
admin = rw

[sample-fastapi:/]
@ml = r

[sample-fastapi:/trunk]
@ml = rw

[sample-react:/]
@ml = r

[sample-react:/trunk]
@ml = rw

[sample-spring:/]
@payment = r

[sample-spring:/trunk]
@payment = rw

