FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get update -qq && \
    apt-get install -qq -y --no-install-recommends \
      nginx \
      openssh-server \
      sudo \
      curl \
      tar \
      ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /var/run/sshd /run/sshd && \
    ssh-keygen -A

RUN useradd -m -s /bin/bash deploy && \
    install -d -m 700 -o deploy -g deploy /home/deploy/.ssh && \
    echo 'deploy ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/deploy && \
    chmod 0440 /etc/sudoers.d/deploy

CMD ["/usr/sbin/sshd","-D"]
