jenkins:
  systemMessage: "Legacy CI/CD Pipeline"
  numExecutors: 5
  securityRealm:
    ldap:
      configurations:
        - server: "${LDAP_URL}"
          rootDN: "${LDAP_BASE_DN}"
          userSearchBase: "${LDAP_USER_BASE}"
          userSearch: "uid={0}"
          groupSearchBase: "${LDAP_ROLE_BASE}"
          managerDN: "${LDAP_BIND_DN}"
          managerPasswordSecret: "${LDAP_BIND_PASSWORD}"
  authorizationStrategy:
    projectMatrix:
      entries:
        - group:
            name: "authenticated"
            permissions:
              - "View/Delete"
              - "View/Read"
              - "View/Configure"
              - "View/Create"
              - "Job/Read"
              - "Job/Build"
              - "Job/Configure"
              - "Job/Create"
              - "Job/Delete"
              - "Job/Discover"
              - "Job/Move"
              - "Job/Workspace"
              - "Job/Cancel"
              - "Run/Delete"
              - "Run/Replay"
              - "Run/Update"
              - "SCM/Tag"
              - "Overall/Administer"
        - user:
            name: "anonymous"
            permissions:
              - "Overall/Read"
jobs:
  - file: /var/jenkins_home/seed/seed.groovy

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: svn-creds
              username: "admin"
              password: "admin"
              description: "SVN Admin Account"

          - usernamePassword:
              id: nexus-creds
              username: "admin"
              password: "admin"
              description: "Nexus Admin Account"

          - string:
              id: "npm-token"
              secret: "YWRtaW46YWRtaW4="
              description: "npm-token"
unclassified:
  location:
    url: "https://jenkins.example.com"
    adminAddress: "admin@example.com"

  mailer:
    smtpHost: "mailhog"
    smtpPort: "1025"

