server {
  listen 80;
  server_name nexus.ghlab.dev;

  return 301 https://$host$request_uri;
}

server {
  listen 80;
  server_name docker.nexus.ghlab.dev;

  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name nexus.ghlab.dev;

  ssl_certificate /etc/nginx/certs/nexus/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/nexus/privkey.pem;

  proxy_send_timeout 120;
  proxy_read_timeout 300;
  proxy_buffering    off;
  proxy_request_buffering off;
  keepalive_timeout  5 5;
  tcp_nodelay        on;
  client_max_body_size 2G;

  resolver 127.0.0.11 valid=10s ipv6=off;
  set $nexus_ui nexus:8081;

  # Regular Nexus requests
  location / {
    proxy_set_header Host $host:$server_port;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto "https";
    proxy_pass http://$nexus_ui;
  }
}

server {
  listen 5000 ssl;
  server_name docker.nexus.ghlab.dev;

  ssl_certificate     /etc/nginx/certs/nexus/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/nexus/privkey.pem;

  client_max_body_size 2G;

  proxy_read_timeout 300;
  proxy_connect_timeout 300;
  proxy_send_timeout 300;

  proxy_buffering off;
  proxy_request_buffering off;

  resolver 127.0.0.11 valid=10s ipv6=off;
  set $nexus_docker_pull nexus:5000;

  location / {

    proxy_pass http://$nexus_docker_pull;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}

server {
  listen 5001 ssl;
  server_name docker.nexus.ghlab.dev;

  ssl_certificate     /etc/nginx/certs/nexus/fullchain.pem;
  ssl_certificate_key /etc/nginx/certs/nexus/privkey.pem;

  client_max_body_size 2G;

  proxy_read_timeout 300;
  proxy_connect_timeout 300;
  proxy_send_timeout 300;

  proxy_buffering off;
  proxy_request_buffering off;

  resolver 127.0.0.11 valid=10s ipv6=off;
  set $nexus_docker_push nexus:5001;

  location / {

    proxy_pass http://$nexus_docker_push;

    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }
}
