server {
    listen 80;
    server_name rundeck.ghlab.dev;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name rundeck.ghlab.dev;

    ssl_certificate /etc/nginx/certs/rundeck/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/rundeck/privkey.pem;

    resolver 127.0.0.11 valid=10s ipv6=off;
    set $rundeck_upstream rundeck:4440;

    location / {
        proxy_pass http://$rundeck_upstream;

        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
